# Generated by Django 5.0.6 on 2024-05-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalperformance',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
